### ISSUE TITLE
Null point exception during FACT algorithm (-mln -approxCount) for WebKB data

### ISSUE THREAD

**Issue by SeongwooLimKR** [boost-starai/BoostSRL#35]
Dear all,

When I run following code,

java -cp boostsrl_v1.1.1.jar edu.wisc.cs.will.Boosting.MLN.RunBoostedMLN -l -train WebKB/train/ -model WebKB/model/ -target faculty -trees 10 -mln -approxCount -aucJarPath .

, following error ocuurs.

![image](https://user-images.githubusercontent.com/11925956/82528510-e09ab100-9b73-11ea-9f77-96da159ae886.png)

How can I fix this problem?

I tested on both of BoostSRL source (stable/nightly) and I used v1.1.1 jar of BoostSRL.
I downloaded the dataset from https://starling.utdallas.edu/datasets/webkb/
I also used openjdk 11.0.6

Thank you,
-Seongwoo

**Comment by harshakokel** [comment]
Hello Seongwoo,

Thank you for bringing this issue to our notice. I ran the above instruction and found that the approximate counting code is expecting a space after "mode:" in the bk file. We will push a fix soon. 

Meanwhile, could you rerun the command with the updated `webkb_bk.txt` file attached here and let us if that works for you? 

Thanks,
Harsha Kokel.

[webkb_bk.txt](https://github.com/starling-lab/BoostSRL/files/4663901/webkb_bk.txt)

**Comment by SeongwooLimKR** [comment]
Hello Harsha,

After update the webkb_bk.txt, the command works well!

Thank you!
-Seongwoo
