### ISSUE TITLE
Question about multi-target dataset

### ISSUE THREAD

**Issue by SeongwooLimKR** [boost-starai/BoostSRL#38]
Dear all,

I have question about multi-target dataset.

There are datasets which have more than one relation as target.
For example,
(1) Cora => samebib, sametitle, sameauthor, samevenue
(2) Citeseer => infield_ftitle, infield_fauthor, infield_fvenue

If we want to run the code with only one relation, e.g. only samebib in Cora (-target samebib), should I move the other evidence about sametitle, sameauthor, samevenue from train(test)_pos(neg) to train(test)_facts?

And When we run the code with onle one relation, e.g. only samebib in Cora (-target samebib), I want to know whether the model will ignore the sametitle, sameauthor, samevenue evidence in train(test)_pos(neg) file or not,

Thank you,
-Seongwoo

**Comment by nandhiniramanan5** [comment]
Hi Seongwoo,

Yes, you must move the evidence about sametitle, sameauthor, samevenue from train(test)_pos(neg) to train(test)_facts, when reasoning about only samebib in Cora .

**Comment by SeongwooLimKR** [comment]
Thank you for your response!

**Comment by SeongwooLimKR** [comment]
Dear all, 

When I move the evidence from train_neg to train_fact, "!" expression is not work.

How can I express the negation of predicate? e.g. samebib(p1,p2)=False =>!samebib(p1,p2)

or Does the BoostSRL only support the closed world assumption?

Thank you,
-Seongwoo

**Comment by nandhiniramanan5** [comment]
BoostSRL makes closed world assumption. So you only have to specify the evidence that are true in the domain.

**Comment by SeongwooLimKR** [comment]
I understand. Thank you!
