### ISSUE TITLE
Supporting BoostRLR?

### ISSUE THREAD

**Issue by SeongwooLimKR** [boost-starai/BoostSRL#41]
Dear BoostSRL team members,

I want to know whether the BoostSRL also supports Boosted Relational Logistic Regression or not.

Thank you,
-Seongwoo

**Comment by harshakokel** [comment]
Hello Seongwoo,

Thank you for your interest in the Boost RLR system. It is available separately in the following repository:

https://github.com/nandhiniramanan5/RLR_Boost

Thanks,
Harsha Kokel.

**Comment by SeongwooLimKR** [comment]
Thanks for your kind response!
-Seongwoo
